# Generated by Django 3.1.5 on 2022-12-24 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('cant_stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_minimo', models.PositiveIntegerField(default=1, verbose_name='Stock Minimo')),
                ('precio_compra', models.BigIntegerField(default=0, verbose_name='Precio compra')),
                ('precio_venta', models.BigIntegerField(default=0, verbose_name='Precio venta')),
                ('iva', models.CharField(choices=[('0', '0%'), ('1', '5%'), ('2', '10%')], default='2', max_length=1)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre ')),
            ],
            options={
                'verbose_name': 'Tipo Producto',
                'verbose_name_plural': 'Tipos Productos',
                'db_table': 'tipo_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_actual', models.PositiveIntegerField(null=True)),
                ('cant_minimo', models.PositiveIntegerField(default=1, verbose_name='Stock Minimo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.tipoproducto'),
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Compra', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Compra')),
                ('precio_compra', models.PositiveIntegerField(default=0, verbose_name='Precio compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'db_table': 'precio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mov', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Mov_Prod')),
                ('cant_mov', models.BigIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=30)),
                ('tipo_movimiento', models.CharField(choices=[('0', 'Entrada'), ('1', 'Salida')], default='1', max_length=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Movimiento Stock',
                'verbose_name_plural': 'Movimientos Stock',
                'db_table': 'movimiento_stock',
                'ordering': ['id'],
            },
        ),
    ]
