# Generated by Django 3.1.5 on 2022-12-24 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('0', 'Abierta'), ('1', 'Cerrada')], default='1', max_length=1)),
                ('saldo_actual', models.BigIntegerField(default=0)),
                ('monto_inicio', models.BigIntegerField(default=0)),
                ('monto_cierre', models.BigIntegerField(default=0)),
                ('total_ingreso', models.BigIntegerField(default=0)),
                ('total_egreso', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'forma_pago',
                'verbose_name_plural': 'Formas de Pagos',
                'db_table': 'forma_pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'moneda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Mov_Caja')),
                ('descripcion', models.CharField(max_length=30)),
                ('tipo_movimiento', models.CharField(choices=[('0', 'Entrada'), ('1', 'Salida')], max_length=1)),
                ('monto_ingreso', models.BigIntegerField(default=0)),
                ('monto_egreso', models.BigIntegerField(default=0)),
                ('monto_inicio', models.BigIntegerField(default=0)),
                ('monto_cierre', models.BigIntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Caja.caja')),
            ],
            options={
                'verbose_name': 'Movimiento Caja',
                'verbose_name_plural': 'Movimientos Cajas',
                'db_table': 'movimiento_caja',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Caja.moneda'),
        ),
    ]
