# Generated by Django 3.1.5 on 2022-12-24 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Compra')),
                ('nro_factura', models.CharField(max_length=20, verbose_name='Factura Compra')),
                ('tipo_compra', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=1, verbose_name='Tipo Compra')),
                ('fecha_plazo', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Plazo')),
                ('subtotal', models.BigIntegerField(default=0)),
                ('iva_0', models.BigIntegerField(default=0)),
                ('iva_5', models.BigIntegerField(default=0)),
                ('iva_10', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComprasDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.BigIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compra Det',
                'verbose_name_plural': 'Compras Det',
                'db_table': 'compra_det',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaXpagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Pagado'), ('1', 'Deuda')], default='0', max_length=1)),
                ('monto_x_pagar', models.BigIntegerField(default=0)),
                ('saldo', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cuenta por pagar',
                'verbose_name_plural': 'Cuentas por pagar',
                'db_table': 'cuenta_x_pagar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Orden')),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Confirmado'), ('2', 'Anulado'), ('3', 'Cerrada')], default='0', max_length=1)),
                ('subtotal', models.BigIntegerField(default=0)),
                ('iva_0', models.BigIntegerField(default=0)),
                ('iva_5', models.BigIntegerField(default=0)),
                ('iva_10', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'ordenCompra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.BigIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Orden Compra Det',
                'verbose_name_plural': 'Ordenes de Compras Det',
                'db_table': 'orden_compra_det',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('ruc', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.datetime.now, verbose_name='Fecha pago')),
                ('monto_pagado', models.BigIntegerField(default=0)),
                ('efectivo', models.BigIntegerField(default=0)),
                ('vuelto', models.BigIntegerField(default=0)),
                ('caja', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Caja.caja')),
                ('cuenta_x_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.cuentaxpagar')),
                ('forma_pago', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Caja.formapago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Cuentas pagadas',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
    ]
