# Generated by Django 3.1.5 on 2022-12-24 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0001_initial'),
        ('Compra', '0001_initial'),
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompradet',
            name='nro_orden_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompradet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.company'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentaxpagar',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.compra'),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.compra'),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.company'),
        ),
        migrations.AddField(
            model_name='compra',
            name='ordenCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.ordencompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Compra.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
