# Generated by Django 3.1.5 on 2022-12-24 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Caja', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='CI')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10, verbose_name='Sexo')),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('ruc', models.CharField(max_length=12, verbose_name='Ruc')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('timbrado', models.CharField(blank=True, max_length=8, null=True, verbose_name='Timbrado')),
                ('fecha_desde', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha hasta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'db_table': 'company',
                'ordering': ['id'],
                'permissions': (('change_company', 'Can change Company'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden_v', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Orden Venta')),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Confirmado'), ('2', 'Anulado')], default='0', max_length=1)),
                ('subtotal', models.BigIntegerField(default=0)),
                ('iva_0', models.BigIntegerField(default=0)),
                ('iva_5', models.BigIntegerField(default=0)),
                ('iva_10', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.cliente')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Venta',
                'verbose_name_plural': 'Ordenes de Ventas',
                'db_table': 'orden_venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Venta')),
                ('tipo_venta', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=1, verbose_name='Tipo Venta')),
                ('fecha_plazo', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Plazo')),
                ('subtotal', models.BigIntegerField(default=0)),
                ('iva_0', models.BigIntegerField(default=0)),
                ('iva_5', models.BigIntegerField(default=0)),
                ('iva_10', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.cliente')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Venta.company')),
                ('ordenVenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.ordenventa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentasDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.BigIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.BigIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.venta')),
            ],
            options={
                'verbose_name': 'Venta Det',
                'verbose_name_plural': 'Ventas Det',
                'db_table': 'venta_det',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenVentaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.BigIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.BigIntegerField(default=0)),
                ('nro_orden_v', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.ordenventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Orden Venta Det',
                'verbose_name_plural': 'Ordenes de Ventas Det',
                'db_table': 'orden_venta_det',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaXcobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Pagado'), ('1', 'Deuda')], default='0', max_length=1)),
                ('monto_x_cobrar', models.BigIntegerField(default=0)),
                ('saldo', models.BigIntegerField(default=0)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'db_table': 'cuenta_x_cobrar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha cobrar')),
                ('monto_cobrado', models.BigIntegerField(default=0)),
                ('efectivo', models.BigIntegerField(default=0)),
                ('vuelto', models.BigIntegerField(default=0)),
                ('caja', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Caja.caja')),
                ('cuenta_x_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Venta.cuentaxcobrar')),
                ('forma_cobro', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Caja.formapago')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cuentas cobradas',
                'db_table': 'cobro',
                'ordering': ['id'],
            },
        ),
    ]
